trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
  - job: Package
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
      - template: devtools/azure/windows-dependencies.yml
        parameters:
          rustup_toolchain: '1.38.0-x86_64-pc-windows-msvc'
      - script: cargo build --release
        displayName: Build
      - powershell: |
          mkdir ckb_slayers_$(Build.SourceBranchName)_x86_64-pc-windows-msvc
          cp -r target/release/slayers.exe,README.md,spec.md ckb_slayers_$(Build.SourceBranchName)_x86_64-pc-windows-msvc
        displayName: Prepare archive
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: 'ckb_slayers_$(Build.SourceBranchName)_x86_64-pc-windows-msvc'
          archiveFile: '$(Build.ArtifactStagingDirectory)/ckb_slayers_$(Build.SourceBranchName)_x86_64-pc-windows-msvc.zip'
      - script: choco install -y gpg4win
        displayName: Install GPG4Win
      - task: DownloadSecureFile@1
        inputs:
          secureFile: azure-secret.asc
      - script: |
          set PATH=%PATH%;%ProgramFiles(x86)%/GnuPG/bin
          gpg --import %DOWNLOADSECUREFILE_SECUREFILEPATH%
          echo "##vso[task.setvariable variable=PATH;]%PATH%;%ProgramFiles(x86)%/GnuPG/bin"
        displayName: Setup GPG
      - script: |
          gpg -u "Nervos Azure Builder <bot@nervos.org>" -ab "$(Build.ArtifactStagingDirectory)/ckb_slayers_$(Build.SourceBranchName)_x86_64-pc-windows-msvc.zip"
        displayName: Sign Archive
      - task: GitHubRelease@0
        inputs:
          gitHubConnection: nervos-bot
          repositoryName: nervosnetwork/ckb
          action: edit
          tag: $(Build.SourceBranchName)
          assets: |
            $(Build.ArtifactStagingDirectory)/*.zip
            $(Build.ArtifactStagingDirectory)/*.asc
          assetUploadMode: replace
          isPreRelease: true
          addChangeLog: false
