[package]
name = "Slayers"
version = "0.1.0"
authors = ["zhangsoledad <787953403@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinytemplate = "1.0"
serde = "1.0"
serde_derive = "1.0"
